package datamaintain.core.util.exception

import datamaintain.core.exception.DatamaintainBaseException

open class DatamaintainQueryException(message: String) : DatamaintainBaseException(message)
